pcb_portal_proto/pcb_app/urls.py
from django.urls import path
from . import views


app_name = 'pcb_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('orders/<int:order_id>/', views.order_details, name='order_details_link'),
    path('orders/place/', views.order_place, name='order_place'),
    path('orders/<int:order_id>/order_item_add', views.order_item_add, name='order_item_add_link'),
    path('orders/', views.order_list, name='order_list_link'),
]

pcb_portal_proto/pcb_portal_proto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pcb_app/', include('pcb_app.urls')),
    path('admin/', admin.site.urls),
]

pcb_portal_proto/pcb_app/models.py
from django.db import models
from django.utils import timezone

import datetime


class Order(models.Model):
    date = models.DateTimeField('order_date', auto_now_add=True)
    currency = models.CharField('order_currency', max_length=3)
    total_cost = models.FloatField('order_total_cost', default=0.0)
    delivery_country = models.CharField('order_delivery', max_length=3)
    is_paid = models.CharField('order_paid', max_length=30)
    is_delivered = models.CharField('order_delivered', max_length=30)
    is_fake = models.CharField('order_is_fake', max_length=30)

    def __str__(self):
        return "Order #%s for %s" % (self.id, self.date)

    def created_this_month(self):
        return self.date >= timezone.now() - datetime.timedelta(days=30)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    sku_id = models.CharField('item_sku', max_length=100)
    type = models.CharField('item_type', max_length=10)
    quantity = models.SmallIntegerField('item_quantity', default=1)

    class Meta:
        abstract = True


class OrderItemPCB(OrderItem):
    size = models.CharField('pcb_item_size', max_length=10)
    material = models.CharField('pcb_item_material', max_length=100)
    thickness = models.FloatField('pcb_item_thickness')
    color = models.CharField('pcb_item_color', max_length=15)
    price = models.FloatField('pcb_item_price', default=0.0)

    def __str__(self):
        return "Printed Circuit Board #%s colored: %s" % (self.id, self.color)


class Vendor(models.Model):
    name = models.CharField('vendor_name', max_length=100)
    country = models.CharField('vendor_country', max_length=100)
    currency = models.CharField('vendor_currency', max_length=100)

    def __str__(self):
        return "Vendor: %s" % self.name


class Sku(models.Model):
    id = models.CharField('sku_id', max_length=10, primary_key=True, db_index=True)
    section_name = models.CharField('sku_section_name', max_length=50)
    type_name = models.CharField('sku_type_name', max_length=10, unique=True)
    value = models.CharField('sku_value', max_length=10)
    description = models.CharField('sku_friendly_description', max_length=100)

    def __str__(self):
        return "SKU #%s: %s - %s (%s)" % (self.id, self.type_name, self.value, self.description)


class VendorInventory(models.Model):
    sku = models.ForeignKey(Sku, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    price = models.PositiveIntegerField('inventory_sku_price', default=0)
    reserve = models.SmallIntegerField('inventory_sku_reserve', default=0)  # may be negative = means "requested"
    last_update_time = models.DateTimeField('inventory_sku_last_update_time', auto_now_add=True)

    def __str__(self):
        return "Inventory line: SKU %s of %s with reserve of %s" % (self.sku, self.vendor, self.reserve)

pcb_portal_proto/pcb_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Order, OrderItemPCB, Sku


def index(request):
    index_page_urls = ['order_list_link',]
    context = {
        'index_page_urls': index_page_urls,
    }
    return render(request, 'pcb_app/index.html', context)


def order_list(request):
    latest_orders_list = Order.objects.order_by('pk')[:5]
    context = {
        'latest_orders_list': latest_orders_list,
    }
    return render(request, 'pcb_app/order_list.html', context)


def order_place(request):
    all_sku_type_names = (sku.type_name for sku in Sku.objects.all())
    context = {
        'sku_type_names': all_sku_type_names
    }
    return render(request, 'pcb_app/order_place.html', context)

# ===============


def order_details(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    current_items = order.orderitempcb_set.all()
    order.total_cost = sum([item.price for item in current_items])

    context = {
        'order': order,
    }
    return render(request, 'pcb_app/order_details.html', context)


def order_create(request):
    try:
        print(request.POST['is_fake'])
        new_order = Order(date=request.POST['date'],
                          currency=request.POST['currency'],
                          delivery_country=request.POST['delivery_country'],
                          is_paid=request.POST['is_paid'],
                          is_delivered=request.POST['is_delivered'],
                          is_fake=request.POST['is_fake'],
                          )
        new_order.save()
    except Exception as ex:
        print("Error is: ", str(ex))
        context = {
            'error_message': 'Error on attempt to add new Order.',
        }
        return render(request, 'pcb_app/order_list.html', context)
    else:
        new_order.save()
        return HttpResponseRedirect(reverse('pcb_app:order_list_link', args=()))


def order_item_add(request, order_id):
    order = Order.objects.get(pk=order_id)
    try:
        new_order_item = OrderItemPCB(order=order,
                                      type=request.POST['type'],
                                      quantity=request.POST['quantity'],
                                      size=request.POST['size'],
                                      material=request.POST['material'],
                                      thickness=request.POST['thickness'],
                                      color=request.POST['color'],
                                      price=request.POST['price'],
                                      )
    except Exception as ex:
        context = {
            'order': order,
            'error_message': "Error on attempt to add new Order Item",
        }
        return render(request, 'pcb_app/order_details.html', context)
    else:
        new_order_item.save()
        return HttpResponseRedirect(reverse('pcb_app:order_details_link', args=(order.id,)))

pcb_portal_proto/pcb_app/templates/pcb_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
</head>
<body>
<ul>
{% for link in index_page_urls %}
    <li>
    <a href="{% url 'pcb_app:order_list_link' %}">link to Orders</a>
    </li>
    <li>
    <a href="{% url 'pcb_app:order_place' %}">Place an Order</a>
    </li>
{% endfor %}
</ul>
</body>
</html>

pcb_portal_proto/pcb_app/templates/pcb_app/order_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
</head>
<body>
<h3>{{ order }} - ${{ order.total_cost }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <ul title="Existent Order Items">
    {% for item in order.orderitempcb_set.all %}
    <li>Order Item: {{ item.material }} - ${{ item.price }}</li>
    {% endfor %}
    </ul>

<form action="{% url 'pcb_app:order_item_add_link' order.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="type" id="type">
    <label for="type">Item type: </label><br>
    <input type="text" name="quantity" id="quantity">
    <label for="quantity">Item quantity: </label><br>
    <input type="text" name="size" id="size">
    <label for="size">Item size: </label><br>
    <input type="text" name="material" id="material">
    <label for="material">Item material: </label><br>
    <input type="text" name="thickness" id="thickness">
    <label for="thickness">Item thickness: </label><br>
    <input type="text" name="color" id="color">
    <label for="color">Item color: </label><br>
    <input type="text" name="price" id="price">
    <label for="color">Item price: </label><br>
    <input type="submit" value="Add Item">
</form>
</body>
</html>

pcb_portal_proto/pcb_app/templates/pcb_app/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order List</title>
</head>
<body>

{% if latest_orders_list %}
<ul>
    {% for order in latest_orders_list %}
    <li><a href="{% url 'pcb_app:order_details_link' order.id %}">{{ order }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No orders are available.</p>
{% endif %}

<form action="{% url 'pcb_app:order_create' %}" method="POST">
    {% csrf_token %}
    <input type="date" name="date" id="date">
    <label for="date">Order date: </label><br>
    <input type="text" name="currency" id="currency">
    <label for="currency">Order currency: </label><br>
    <input type="text" name="delivery_country" id="delivery_country">
    <label for="delivery_country">Order delivery country: </label><br>
    <input type="text" name="is_paid" id="is_paid">
    <label for="is_paid">Order is paid: </label><br>
    <input type="text" name="is_delivered" id="is_delivered">
    <label for="is_delivered">Order is delivered: </label><br>
    <input type="text" name="is_fake" id="is_fake">
    <label for="is_fake">Order is fake: </label><br>
    <input type="submit" value="Add Order">
</form>

</body>
</html>

pcb_portal_proto/pcb_app/templates/pcb_app/order_place.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Place an Order</title>
</head>
<body>

{% if sku_type_names %}
<form action="{% url 'pcb_app:link' %}" method="POST">
    {% csrf_token %}
    {% for sku_name in sku_type_names %}
    <input type="text" name="{% sku_name %}" id="{% sku_name %}">
    <label for="{% sku_name %}">{% sku_name %}: </label><br>
</form>
{% endif %}

</body>
</html>